### ISSUE TITLE
Mirror

### ISSUE THREAD

**Issue by jlippold** [sbingner/plutil#1]
Hey Sam,

Do you mind if I mirror your fork of the plutil deb on my repo? I'm using plutil as a dependency in an app I wrote. I'd use your same packageId and version of course

Thanks

**Comment by sbingner** [comment]
I’ll see about getting it in a default repo.  Don’t really want it hosted a bunch of places because bug fixes or updates won’t make it out everywhere

**Comment by jlippold** [comment]
Ok I’ll point people at your repo then, thanks
